apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: docker.io/saarwasserman/demo-python-app
    newName: docker.io/saarwasserman/demo-python-app # {"$imagepolicy": "flux-system:demo-python-app:name"}
    newTag: v0.1.4 # {"$imagepolicy": "flux-system:demo-python-app:tag"}
