apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: docker.io/saarwasserman/demo-python-app
    newTag: docker.io/saarwasserman/demo-python-app:v0.1.2 # {"$imagepolicy": "flux-system:demo-python-app"}
