apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.appVersion | replace "." "-" }}
  namespace: apps
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Values.appVersion }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Values.appVersion | replace "." "-" }}
      version: {{ .Values.appVersion }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Values.appVersion | replace "." "-" }}
        version: {{ .Values.appVersion }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: docker.io/saarwasserman/{{ .Chart.Name }}:{{ .Values.appVersion }} 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "1Mi"
            cpu: "10m"
        ports:
        - containerPort: 8000
