apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  namespace: apps
  labels:
    app: hello-python
    version: 1.0.0
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: saarwasserman/hello-python:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "1Mi"
            cpu: "10m"
        ports:
        - containerPort: 8000
