apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-python-app
  namespace: apps
  labels:
    app: demo-python-app
    version: 1.0.0
spec:
  selector:
    matchLabels:
      app: demo-python-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-python-app
    spec:
      containers:
      - name: demo-python-app
        image: saarwasserman/demo-python-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "1Mi"
            cpu: "10m"
        ports:
        - containerPort: 8000
