apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-python-app
  namespace: apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-python-app
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

  

  