

# updated by fluxcd image automation controller
# I moved this value here from the Chart.yaml for two reasons:
# 1. It seems fluxcd can update the values file but not the Chart.yaml
#    so i didn't want to start adding scripts to the ci/cd pipeline
# 2. avoid confusion with the appVersion in Chart.yaml
appVersion: v0.1.5

minReplicas: 2
maxReplicas: 3
