

# updated by flux cd image automation
# I moved this value here from the Chart.yaml for two reasons:
# 1. It seems fluxcd can update the values file but not the Chart.yaml
#    so i didn't want to start adding scripts to the ci/cd pipeline
# 2. 
appVersion: v0.1.5
