name: Build Docker Image with Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  Build-and-Push-Docker-Image:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Get tag name
          id: get_tag
          run: |
            echo "The tag that triggered the workflow: ${{ github.ref }}"
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: Dockerfile
            push: true
            platforms: linux/amd64,linux/arm64
            tags: ${{ vars.DOCKERHUB_USERNAME }}/demo-python-app:${{ env.TAG_NAME }}
            cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/demo-python-app:cache
            cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/demo-python-app:cache,mode=max
