name: Release Merge Workflow

on:
  push:
    tags:
      - 'v*'  # Trigger on any version tag (e.g., v1.0.0, v2.1.3)

jobs:
  release-process:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  # Checkout the commit associated with the tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ vars.DOCKERHUB_USERNAME }}/demo-python-app:${GITHUB_REF##*/}
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/demo-python-app:cache
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/demo-python-app:cache,mode=max
